server:
  error:
    include-message: always
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
  datasource:
    url: ${POSTGRESQL_URL:jdbc:postgresql://localhost:5432/app}
    username: ${POSTGRESQL_USER:pismo}
    password: ${POSTGRESQL_PASSWORD:pismo}
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:/db/migration/dev
    url: ${POSTGRESQL_URL:jdbc:postgresql://localhost:5432/app}
    user: ${POSTGRESQL_USER:pismo}
    password: ${POSTGRESQL_PASSWORD:pismo}
    baselineOnMigrate: true